name: My First Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: say hello
        run: echo "Hello, my first workflow!"
